# Generated by Django 3.1.5 on 2021-03-01 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fields_of_study',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.fieldofstudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15)),
                ('type', models.CharField(choices=[('L', 'Lecture'), ('P', 'Practice')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('occupancy', models.PositiveSmallIntegerField(default=0)),
                ('limit', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='api.department')),
            ],
            options={
                'db_table': 'years',
            },
        ),
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'university_admins',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('university_admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='api.universityadmin')),
            ],
            options={
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_types', to='api.fieldofstudy')),
            ],
            options={
                'db_table': 'subjects_types',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='api.subject')),
            ],
            options={
                'db_table': 'subject_groups',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.subjecttype'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.subject')),
            ],
            options={
                'db_table': 'points',
            },
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='api.year'),
        ),
        migrations.CreateModel(
            name='DepartmentAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_admins', to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department_admins',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.university'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.student')),
                ('unwanted_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unwanted_applications', to='api.subject')),
                ('wanted_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_applications', to='api.subject')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(fields=('department', 'start_year'), name='unique_year'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroup',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='unique_subject_group'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('field_of_study', 'user'), name='unique_student'),
        ),
        migrations.AddConstraint(
            model_name='points',
            constraint=models.UniqueConstraint(fields=('subject', 'student'), name='unique_points'),
        ),
        migrations.AddConstraint(
            model_name='fieldofstudy',
            constraint=models.UniqueConstraint(fields=('year', 'name'), name='unique_field_of_study'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_department'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('unwanted_subject', 'wanted_subject', 'student'), name='unique_application'),
        ),
    ]
