# Generated by Django 3.1.5 on 2021-01-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('university', 'university_admin', 'name'), name='unique_department'),
        ),
        migrations.AddConstraint(
            model_name='fieldofstudy',
            constraint=models.UniqueConstraint(fields=('year', 'name'), name='unique_field_of_study'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('field_of_study', 'name'), name='unique_subject'),
        ),
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(fields=('department', 'start_year'), name='unique_year'),
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='departmentadmin',
            table='department_admins',
        ),
        migrations.AlterModelTable(
            name='fieldofstudy',
            table='fields_of_study',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='subjectgroup',
            table='subject_groups',
        ),
        migrations.AlterModelTable(
            name='university',
            table='universities',
        ),
        migrations.AlterModelTable(
            name='universityadmin',
            table='university_admins',
        ),
        migrations.AlterModelTable(
            name='year',
            table='years',
        ),
    ]
